server:
    port: 8888

spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        # local DB
#        url: jdbc:mariadb://localhost:3306/encore?useUnicode=true
#        username: root
#        password: 123456789

        # cloud
        url: jdbc:mariadb://localhost:6033/encore?useUnicode=true
        username: work_user
        password: work_password

mybatis:
    mapper-locations: mappers/*.xml