name : Java with Gradle
on :
  push :
    branches : [main]
jobs :
  build :
    runs-on:  ubuntu-latest
      # runner 설치 (os)
    steps :
    # runner에 소스코드 설치
    - name : Source Checkout
      uses : actions/checkout@v2
    # JAVA 버전 설정
    - name : Setup JDK 17
      uses : actions/setup-java@v2
      with :
        java-version : '17'
        distribution : 'adopt'
    # jar파일 build 및 permission
    - name : Grant jar
      run : chmod +x gradlew
    - name : Build jar
      run : ./gradlew build bootJAR
      # action이 모든 step의 명령어를 갖는 것은 아니기에
      # 이렇게 직접 명령어를 지정해야할 때는 run을 사용해야 한다.
    # runner(ubuntu) docker buildx install
    - name : Docker buildx
      uses : docker/setup-buildx-action@v2
    # docker login
    - name : Docker Login
      uses : docker/login-action@v2
      with :
        username : ${{ secrets.DOCKERHUB_USERNAME }}
        password : ${{ secrets.DOCKERHUB_TOKEN }}
    # docker image build to push docker hub
    - name : Push Image
      uses : docker/build-push-action@v2
      with :
        # image로 만들 내용의 위치
        context : ./
        # docker파일의 위치
        file : ./Dockerfile
        push : true
        # build될 Image의 이름
        tags : ${{ secrets.DOCKERHUB_USERNAME }}/vue-spring-pjt:${{github.sha}}